name: Deployer

on:
  workflow_call:
    inputs:
      deployer-version:
        default: "7.0.0"
        required: false
        type: string
      environment:
        required: true
        type: string
      php-version:
        required: true
        type: string
    secrets:
      private-key:
        required: true
      slack-url:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use Checkout
        uses: actions/checkout@v3.0.2

      - name: Use PHP ${{ inputs.php-version }}
        uses: shivammathur/setup-php@2.21.1
        with:
          php-version: ${{ inputs.php-version }}

      - name: Deploy
        uses: deployphp/action@v1.0.17
        with:
          dep: deploy -o slack_webhook=${{ secrets.slack-url }} --revision=${{ github.sha }} ${{ inputs.environment }}
          deployer-version: ${{ inputs.deployer-version }}
          private-key: ${{ secrets.private-key }}
