name: Node.js

on:
  workflow_call:
    inputs:
      run-eslint:
        default: true
        required: false
        type: boolean
      run-stylelint:
        default: true
        required: false
        type: boolean
      update-browserslist:
        default: true
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Checkout
        uses: actions/checkout@v2.4.0

      - name: Use Node.js
        uses: actions/setup-node@v2.5.1
        with:
          cache: "npm"
          node-version-file: ".nvmrc"

      - name: Install Dependencies
        run: npm install --quiet

      - name: Update Browserlist
        if: ${{ inputs.update-browserslist }}
        run: npx browserslist@latest --update-db

      - name: Run eslint
        if: ${{ inputs.run-eslint }}
        run: npm run eslint

      - name: Run stylelint
        if: ${{ inputs.run-stylelint }}
        run: npm run stylelint

      - name: Run production
        run: npm run production
