name: Node.js

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Checkout
        uses: actions/checkout@v2.4.0

      - name: Use Node.js
        uses: actions/setup-node@v2.5.0
        with:
          cache: "npm"
          node-version-file: ".nvmrc"

      - name: Install Dependencies
        run: npm install --quiet

      - name: Update Browserlist
        run: npx browserslist@latest --update-db

      - name: Run eslint
        run: npm run eslint

      - name: Run stylelint
        run: npm run stylelint

      - name: Run production
        run: npm run production
