name: PHP

on:
  workflow_call:
    inputs:
      php-version:
        required: true
        type: string
      run-phpcs:
        default: false
        required: false
        type: boolean
      run-twigcs:
        default: false
        required: false
        type: boolean
      use-composer-auth:
        default: false
        required: false
        type: boolean
    secrets:
      composer-auth-json:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Checkout
        uses: actions/checkout@v4.1.4

      - name: Use PHP ${{ inputs.php-version }} With Composer 2
        uses: shivammathur/setup-php@2.30.4
        with:
          php-version: ${{ inputs.php-version }}
          tools: composer:v2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Use Composer Cache Directory
        uses: actions/cache@v4.0.2
        with:
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          path: ${{ steps.composer-cache.outputs.dir }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Validate Composer Files
        run: composer validate

      - name: Add Composer Authentication
        if: ${{ inputs.use-composer-auth }}
        run: echo '${{ secrets.composer-auth-json }}' > $GITHUB_WORKSPACE/auth.json

      - name: Install Composer Dependencies
        run: composer install --no-interaction --no-progress --prefer-dist --verbose

      - name: Remove Composer Authentication
        if: ${{ inputs.use-composer-auth }}
        run: rm -f $GITHUB_WORKSPACE/auth.json

      - name: Run PHP_CodeSniffer
        if: ${{ inputs.run-phpcs }}
        run: composer run-script phpcs

      - name: Run Twigcs
        if: ${{ inputs.run-twigcs }}
        run: composer run-script twigcs
